# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

align12 <- function(Zmatrix, Wmatrix, sTemp1, traitsCo, traitNo, rho, trait_cor, EPS) {
    .Call('_hyprmtc_align12', PACKAGE = 'hyprcoloc', Zmatrix, Wmatrix, sTemp1, traitsCo, traitNo, rho, trait_cor, EPS)
}

align1 <- function(Zmatrix, Wmatrix, N_CV, traitsCo, traitNo, trait_cor, rho, EPS) {
    .Call('_hyprmtc_align1', PACKAGE = 'hyprcoloc', Zmatrix, Wmatrix, N_CV, traitsCo, traitNo, trait_cor, rho, EPS)
}

align1ind <- function(Zmatrix, Wmatrix, traitsCo, traitNo) {
    .Call('_hyprmtc_align1ind', PACKAGE = 'hyprcoloc', Zmatrix, Wmatrix, traitsCo, traitNo)
}

align2 <- function(Zmatrix, Wmatrix, sTemp1, traitsCo, traitNo, rho, trait_cor, EPS) {
    .Call('_hyprmtc_align2', PACKAGE = 'hyprcoloc', Zmatrix, Wmatrix, sTemp1, traitsCo, traitNo, rho, trait_cor, EPS)
}

regional1 <- function(zTemp1, wTemp1, traitsCo, trait_cor, EPS) {
    .Call('_hyprmtc_regional1', PACKAGE = 'hyprcoloc', zTemp1, wTemp1, traitsCo, trait_cor, EPS)
}

regional1ind <- function(zTemp1, wTemp1, traitsCo) {
    .Call('_hyprmtc_regional1ind', PACKAGE = 'hyprcoloc', zTemp1, wTemp1, traitsCo)
}

regional2 <- function(zTemp1, wTemp1, sTemp1, traitsCo, rho, trait_cor, EPS) {
    .Call('_hyprmtc_regional2', PACKAGE = 'hyprcoloc', zTemp1, wTemp1, sTemp1, traitsCo, rho, trait_cor, EPS)
}

